export const ADD_NEW_REPOSITORY = "ADD_NEW_REPOSITORY";
export const FAVORITE_REPOSITORY = "FAVORITE_REPOSITORY";
export const DELETE_REPOSITORY = "DELETE_REPOSITORY";
export const FILTER_BY_NAME = "FILTER_BY_NAME";
export const FILTER_BY_FAVORITE = "FILTER_BY_FAVORITE";
export const SORT_BY_AGE = "SORT_BY_AGE";
